do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'activity_category'
  ) then
    create type activity_category as enum ('meal', 'tour', 'ticketed', 'general');
  end if;
end
$$;

create table if not exists activities (
  activity_id bigint generated by default as identity primary key,
  destination_id bigint not null references destinations (destination_id) on delete cascade,
  category activity_category not null default 'general',
  name text not null,
  day_number integer not null check (day_number >= 1),
  start_time time,
  end_time time,
  position integer not null default 0 check (position >= 0),
  notes text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_activities_destination_day
  on activities (destination_id, day_number, position);

drop trigger if exists activities_updated_at on activities;
create trigger activities_updated_at
before update on activities
for each row execute function update_updated_at();

alter table activities enable row level security;
alter table activities force row level security;

drop policy if exists "Users manage own activities" on activities;
create policy "Users manage own activities"
  on activities
  for all
  to authenticated
  using (
    exists (
      select 1
      from destinations as d
      join trips as t on t.trip_id = d.trip_id
      where d.destination_id = activities.destination_id
        and t.user_id = (select current_user_id())
    )
  )
  with check (
    exists (
      select 1
      from destinations as d
      join trips as t on t.trip_id = d.trip_id
      where d.destination_id = activities.destination_id
        and t.user_id = (select current_user_id())
    )
  );
