-- Phase 2.3: Core schema for TripAIvisor (public schema)

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'transport_type'
  ) then
    create type transport_type as enum ('plane', 'train', 'bus');
  end if;

  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'transport_role'
  ) then
    create type transport_role as enum ('destination', 'departure', 'return');
  end if;
end
$$;

create table if not exists users (
  user_id bigint generated by default as identity primary key,
  email text not null unique,
  name text,
  image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists sessions (
  session_id bigint generated by default as identity primary key,
  user_id bigint not null references users (user_id) on delete cascade,
  expires_at timestamptz not null,
  token text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_sessions_user_id on sessions (user_id);

create table if not exists accounts (
  account_id bigint generated by default as identity primary key,
  user_id bigint not null references users (user_id) on delete cascade,
  provider text not null,
  provider_account_id text not null,
  access_token text,
  refresh_token text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_account_id)
);

create index if not exists idx_accounts_user_id on accounts (user_id);

create table if not exists trips (
  trip_id bigint generated by default as identity primary key,
  user_id bigint not null references users (user_id) on delete cascade,
  title text not null default 'Mi Viaje',
  start_date date,
  departure_city text not null default 'Buenos Aires',
  return_city text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_trips_user_id on trips (user_id);

create table if not exists destinations (
  destination_id bigint generated by default as identity primary key,
  trip_id bigint not null references trips (trip_id) on delete cascade,
  city text not null,
  duration integer not null default 2 check (duration >= 1),
  position integer not null check (position >= 0),
  notes text,
  budget numeric(10,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_destinations_trip_position
  on destinations (trip_id, position);

create table if not exists transports (
  transport_id bigint generated by default as identity primary key,
  destination_id bigint references destinations (destination_id) on delete cascade,
  trip_id bigint references trips (trip_id) on delete cascade,
  transport_role transport_role not null,
  transport_type transport_type not null default 'plane',
  leave_accommodation_time time,
  terminal text,
  company text,
  booking_number text,
  booking_code text,
  departure_time time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint transport_single_parent check (
    (destination_id is not null and trip_id is null and transport_role = 'destination')
    or
    (destination_id is null and trip_id is not null and transport_role in ('departure', 'return'))
  )
);

create unique index if not exists uq_transports_destination
  on transports (destination_id)
  where destination_id is not null;

create unique index if not exists uq_transports_trip_role
  on transports (trip_id, transport_role)
  where trip_id is not null;

create index if not exists idx_transports_destination
  on transports (destination_id)
  where destination_id is not null;

create index if not exists idx_transports_trip
  on transports (trip_id)
  where trip_id is not null;

create table if not exists accommodations (
  accommodation_id bigint generated by default as identity primary key,
  destination_id bigint not null references destinations (destination_id) on delete cascade,
  name text,
  check_in time,
  check_out time,
  booking_link text,
  booking_code text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_accommodations_destination
  on accommodations (destination_id);

create table if not exists trip_shares (
  share_id bigint generated by default as identity primary key,
  trip_id bigint not null references trips (trip_id) on delete cascade,
  share_token text not null unique,
  is_active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_trip_shares_trip_id on trip_shares (trip_id);

create index if not exists idx_trip_shares_active_token
  on trip_shares (share_token)
  where is_active = true;

create or replace function update_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_updated_at on users;
create trigger users_updated_at
before update on users
for each row execute function update_updated_at();

drop trigger if exists sessions_updated_at on sessions;
create trigger sessions_updated_at
before update on sessions
for each row execute function update_updated_at();

drop trigger if exists accounts_updated_at on accounts;
create trigger accounts_updated_at
before update on accounts
for each row execute function update_updated_at();

drop trigger if exists trips_updated_at on trips;
create trigger trips_updated_at
before update on trips
for each row execute function update_updated_at();

drop trigger if exists destinations_updated_at on destinations;
create trigger destinations_updated_at
before update on destinations
for each row execute function update_updated_at();

drop trigger if exists transports_updated_at on transports;
create trigger transports_updated_at
before update on transports
for each row execute function update_updated_at();

drop trigger if exists accommodations_updated_at on accommodations;
create trigger accommodations_updated_at
before update on accommodations
for each row execute function update_updated_at();

-- Grants for public schema (automatically exposed by PostgREST)
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on table trip_shares to anon;
grant usage, select on all sequences in schema public to authenticated, service_role;

alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;

alter default privileges in schema public
  grant usage, select on sequences to authenticated, service_role;
