-- Align Better Auth schema with current auth configuration

alter table users
  add column if not exists email_verified boolean not null default false;

alter table sessions
  add column if not exists ip_address text,
  add column if not exists user_agent text;

alter table accounts
  add column if not exists id_token text,
  add column if not exists scope text;

create table if not exists verification (
  id bigint generated by default as identity primary key,
  identifier text not null,
  value text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_verification_identifier
  on verification (identifier);

drop trigger if exists verification_updated_at on verification;
create trigger verification_updated_at
before update on verification
for each row execute function update_updated_at();
