create table if not exists transport_legs (
  leg_id bigint generated by default as identity primary key,
  transport_id bigint not null references transports (transport_id) on delete cascade,
  position integer not null check (position >= 0),
  origin_city text,
  destination_city text,
  company text,
  booking_number text,
  booking_code text,
  departure_time time,
  arrival_time time,
  day_offset integer not null default 0 check (day_offset >= 0),
  terminal text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (transport_id, position)
);

create index if not exists idx_transport_legs_transport_id on transport_legs (transport_id);

create or replace function decrement_leg_positions(p_transport_id bigint, p_after_position integer)
returns void
language sql
as $$
  update transport_legs
  set position = position - 1
  where transport_id = p_transport_id
    and position > p_after_position;
$$;

drop trigger if exists transport_legs_updated_at on transport_legs;
create trigger transport_legs_updated_at
before update on transport_legs
for each row execute function update_updated_at();
